# Generated by Django 4.1.4 on 2023-06-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='Task',
            field=models.CharField(max_length=300),
        ),
    ]
