# Generated by Django 4.1.4 on 2023-06-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_alter_tasklist_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='Task',
            new_name='task',
        ),
    ]
