# Generated by Django 4.2.2 on 2023-06-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0005_alter_tasklist_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['id']},
        ),
    ]
